import * as React from 'react';
import { Link, createRoute } from '@tanstack/react-router';
import { ArrowLeft } from 'lucide-react';
import { AuthGuard } from '@/components/AuthGuard';
import { AppShell } from '@/components/AppShell';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { SegmentRow } from '@/components/SegmentRow';
import { FauteCard } from '@/components/FauteCard';
import { api } from '@/lib/api';
import {
  SdkError,
  type SdkRecordingSession,
  type SdkSegment,
} from '@fluentquest/sdk';
import type { UiFaute } from '@/types/review';
import { Route as rootRoute } from './__root';

const PLACEHOLDER_FAUTES: UiFaute[] = [
  {
    id: 'demo-1',
    originalText: 'he act',
    correctedText: 'he acts',
    category: 'grammar',
    severity: 3,
    ruleSummary: 'Third-person singular: verbs in present simple take an -s ending.',
    ruleDeep:
      'In English, verbs conjugated in the present simple add an "-s" (or "-es", "-ies") when the subject is third-person singular (he, she, it, or any singular noun).\n\nExamples:\n- He plays football every Saturday.\n- She watches TV every night.\n- It rains a lot here.\n\nCommon mistake: forgetting the -s with "he/she/it".',
    speakerLabel: 'S1',
    startMs: 12_300,
  },
  {
    id: 'demo-2',
    originalText: 'I have went',
    correctedText: 'I have gone',
    category: 'grammar',
    severity: 4,
    ruleSummary: 'Present perfect uses the past participle, not the simple past.',
    speakerLabel: 'S1',
    startMs: 41_780,
  },
];

function fakeDeepLoader(_id: string): Promise<string> {
  return new Promise((resolve) =>
    setTimeout(
      () =>
        resolve(
          'Deep rule explanation will be generated by the LLM once the analysis pipeline (M6) is live.',
        ),
      300,
    ),
  );
}

function SessionDetailPage() {
  const { workspaceId, sessionId } = Route.useParams();
  const [session, setSession] = React.useState<SdkRecordingSession | null>(null);
  const [segments, setSegments] = React.useState<SdkSegment[]>([]);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    api
      .getRecordingSession(sessionId)
      .then((data) => {
        if (cancelled) return;
        setSession(data.session);
        setSegments(data.segments);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        if (err instanceof SdkError && err.status === 404) {
          setError('Session not found.');
        } else {
          setError(err instanceof Error ? err.message : 'Failed to load session.');
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [sessionId]);

  return (
    <AuthGuard>
      <AppShell>
        <div className="mx-auto max-w-5xl space-y-6">
          <div>
            <Button asChild variant="ghost" size="sm">
              <Link
                to="/workspaces/$workspaceId/sessions"
                params={{ workspaceId }}
              >
                <ArrowLeft className="h-4 w-4" />
                Back to sessions
              </Link>
            </Button>
          </div>

          {loading ? (
            <p className="text-sm text-[var(--muted-foreground)]">Loading…</p>
          ) : error ? (
            <Card className="p-6 text-[var(--destructive)]">{error}</Card>
          ) : session ? (
            <>
              <header className="space-y-2">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge variant={session.endedAt ? 'secondary' : 'default'}>
                    {session.endedAt ? 'Completed' : 'Live'}
                  </Badge>
                  <Badge variant="outline">{session.transcriptionStatus}</Badge>
                  {session.languages.map((l) => (
                    <Badge key={l} variant="outline">
                      {l.toUpperCase()}
                    </Badge>
                  ))}
                </div>
                <h1 className="text-2xl font-bold tracking-tight">
                  {session.title ?? 'Untitled session'}
                </h1>
                <p className="text-sm text-[var(--muted-foreground)]">
                  Started {new Date(session.startedAt).toLocaleString()} ·{' '}
                  {Math.floor(session.durationSec / 60)}m {Math.floor(session.durationSec % 60)}s
                </p>
              </header>

              <Card>
                <CardHeader>
                  <CardTitle>Transcript</CardTitle>
                  <CardDescription>
                    Verbatim transcription — errors are preserved on purpose.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {segments.length === 0 ? (
                    <p className="text-sm text-[var(--muted-foreground)]">
                      No segments yet. The desktop client uploads them after transcription.
                    </p>
                  ) : (
                    <div className="space-y-1">
                      {segments.map((s) => (
                        <SegmentRow key={s.id} segment={s} />
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Corrections</CardTitle>
                  <CardDescription>
                    Placeholder data — the LLM analysis pipeline (M6) will replace these.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  {PLACEHOLDER_FAUTES.map((f) => (
                    <FauteCard key={f.id} faute={f} loadRuleDeep={fakeDeepLoader} />
                  ))}
                </CardContent>
              </Card>
            </>
          ) : null}
        </div>
      </AppShell>
    </AuthGuard>
  );
}

export const Route = createRoute({
  getParentRoute: () => rootRoute,
  path: '/workspaces/$workspaceId/sessions/$sessionId',
  component: SessionDetailPage,
});
